apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spoke-dev-games-dev
  namespace: argocd1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: spoke-dev-games-dev
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games-dev
    cloudman.io/creator: Anderson-Dutra
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: proj2
  source:
    repoURL: "https://github.com/Struct8/TestArgo.git"
    targetRevision: HEAD
    path: 378780514943/Games-dev/templates
  destination:
    name: spoke-dev
    namespace: gamestest-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
