apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress-gateway
  namespace: gateway
  labels:
    app.kubernetes.io/name: default-deny-ingress-gateway
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: k3s
    cloudman.io/creator: Templates
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
