apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false,Delete=false"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: pvc1
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games1
    cloudman.io/user: rmay-struct
  namespace: gamestest1
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-volume-k8spoke
  storageClassName: ""
  resources:
    requests:
      storage: "1Gi"
