apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-kuma1-v1-sa
  labels:
    app.kubernetes.io/name: deployment-kuma1-v1-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games1
    cloudman.io/user: rmay-struct
  namespace: gamestest1
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
