apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-dev
  labels:
    app.kubernetes.io/name: kuma-dev
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games-dev
    cloudman.io/creator: rmay-struct
  namespace: gamestest-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-kuma-dev-v1-sa
      containers:
        - image: "louislam/uptime-kuma:1"
          imagePullPolicy: IfNotPresent
          name: uptime-kuma
          stdin: false
          stdinOnce: false
          tty: false
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          volumeMounts:
            - name: pvc-dev
              mountPath: /app/data
      volumes:
        - name: pvc-dev
          persistentVolumeClaim:
            claimName: pvc-dev
    metadata:
      labels:
        app.kubernetes.io/name: kuma-dev
  selector:
    matchLabels:
      app.kubernetes.io/name: kuma-dev
