apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dev
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false,Delete=false"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: pvc-dev
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games-dev
    cloudman.io/creator: rmay-struct
  namespace: gamestest-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-volume-k8spoke
  storageClassName: ""
  resources:
    requests:
      storage: "1Gi"
