apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-kuma-dev-v1-sa
  labels:
    app.kubernetes.io/name: deployment-kuma-dev-v1-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games-dev
    cloudman.io/creator: rmay-struct
  namespace: gamestest-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
