apiVersion: v1
kind: Service
metadata:
  name: probe-c-svc
  namespace: probe-lab
  labels:
    app.kubernetes.io/name: probe-c-svc
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Chart
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: probe-c
  ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
