apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-probe-a-v1-sa
  labels:
    app.kubernetes.io/name: deployment-probe-a-v1-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Chart
    cloudman.io/user: rmay-struct
  namespace: probe-lab
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
