apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncope-core
  labels:
    app.kubernetes.io/name: syncope-core
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Syncope
    cloudman.io/user: rmay-struct
  namespace: syncope
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: syncope-core-sa
      containers:
        - image: "apache/syncope:4.1.1"
          imagePullPolicy: IfNotPresent
          name: syncope-core
          stdin: false
          stdinOnce: false
          tty: false
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,postgresql"
            - name: DB_POOL_MAX
              value: "20"
            - name: DB_POOL_MIN
              value: "5"
            - name: OPENJPA_REMOTE_COMMIT
              value: "sjvm"
            - name: KEYMASTER_ADDRESS
              value: "http://localhost:8080/syncope/rest/keymaster"
            - name: SERVICE_DISCOVERY_ADDRESS
              value: "http://localhost:8080/syncope/rest/"
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_PORT
              value: "5432"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          envFrom:
            - secretRef:
                name: syncope-anonymous-secret
            - secretRef:
                name: syncope-db-secret
    metadata:
      labels:
        app.kubernetes.io/name: syncope-core
  selector:
    matchLabels:
      app.kubernetes.io/name: syncope-core
