apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: syncope-apps-syncope-enduser
  namespace: syncope
  labels:
    app.kubernetes.io/name: syncope-apps-syncope-enduser
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Syncope
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - name: gapi
      namespace: infra
      sectionName: g-api3
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /syncope-enduser
      backendRefs:
        - name: syncope-enduser-svc
          namespace: syncope
          port: 80
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            statusCode: 302
            path:
              type: ReplaceFullPath
              replaceFullPath: /syncope-enduser/
            hostname: syncope-self.k8s.admin.billingpay.com.br
            scheme: https
  hostnames:
    - syncope-self.k8s.admin.billingpay.com.br
