apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: syncope-apps-syncope-core
  namespace: syncope
  labels:
    app.kubernetes.io/name: syncope-apps-syncope-core
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Syncope
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - name: gapi
      namespace: infrab
      sectionName: g-api3
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: syncope-core-svc
          namespace: syncope
          port: 80
  hostnames:
    - syncope.k8s.admin.billingpay.com.br
