apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: syncope
  labels:
    app.kubernetes.io/name: postgres-svc
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Syncope
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: port-5432
      port: 5432
      targetPort: 5432
      protocol: TCP
