apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-kong1-v1-sa
  labels:
    app.kubernetes.io/name: deployment-kong1-v1-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Chart2
    cloudman.io/creator: Anderson-Dutra
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
