apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: op-kube-prometheus-stack
  namespace: argocd2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: op-kube-prometheus-stack
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: k3s
    cloudman.io/creator: Anderson-Dutra
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    chart: kube-prometheus-stack
    targetRevision: 65.2.0
    helm:
      valuesObject:
        prometheusOperator:
          enabled: true
        prometheus:
          enabled: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kubeStateMetrics:
          enabled: true
        nodeExporter:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
