apiVersion: v1
kind: Namespace
metadata:
  name: probe-lab
  labels:
    app.kubernetes.io/name: probe-lab
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: k3s
    cloudman.io/creator: Templates
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
