apiVersion: v1
kind: Namespace
metadata:
  name: struct8-agent-k3s
  labels:
    app.kubernetes.io/name: struct8-agent-k3s
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: k3s
    cloudman.io/creator: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
