apiVersion: v1
kind: Namespace
metadata:
  name: probe-lab
  labels:
    app.kubernetes.io/name: probe-lab
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Kuster_Ricardo
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
