apiVersion: v1
kind: Secret
metadata:
  name: secret1
  labels:
    app.kubernetes.io/name: secret1
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Chart2
    cloudman.io/user: rmay-struct
  namespace: gamestest
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  WORDPRESS_DB_PASSWORD: V29yZFByZXNzUmRzMjAyNg==
