apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: wordpress
    cloudman.io/user: rmay-struct
  namespace: wp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      restartPolicy: Always
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-wordpress-v1-sa
      containers:
        - image: "wordpress:6-apache"
          imagePullPolicy: IfNotPresent
          name: wordpress
          stdin: false
          stdinOnce: false
          tty: false
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql-svc:3306"
            - name: WORDPRESS_DB_USER
              value: "wordpress"
            - name: WORDPRESS_DB_PASSWORD
              value: "CHANGEME-test-only"
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
            - name: MYSQL_HOST
              value: "mysql-svc"
            - name: MYSQL_PORT
              value: "3306"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
    metadata:
      labels:
        app.kubernetes.io/name: wordpress
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
