apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app.kubernetes.io/name: mysql-secret
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: wordpress
    cloudman.io/user: rmay-struct
  namespace: wp
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  MYSQL_ROOT_PASSWORD: Q0hBTkdFTUUtdGVzdC1vbmx5
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: d29yZHByZXNz
  MYSQL_PASSWORD: Q0hBTkdFTUUtdGVzdC1vbmx5
