apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-wordpress-v1-sa
  labels:
    app.kubernetes.io/name: deployment-wordpress-v1-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: wordpress
    cloudman.io/user: rmay-struct
  namespace: wp
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
