apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-k3s
  labels:
    app.kubernetes.io/name: prometheus-k3s
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent1-k3s
    cloudman.io/creator: rmay-struct
  namespace: struct8-agent-k3s
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  serviceAccountName: prometheus-prometheus-k3s-sa
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
