apiVersion: v1
kind: Secret
metadata:
  name: struct8-agent-k3s-secret
  namespace: struct8-agent-k3s
  labels:
    app.kubernetes.io/name: struct8-agent-k3s-secret
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent1-k3s
    cloudman.io/creator: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
data:
  CLUSTER_API_KEY: azhzX0kzSEV6NGxXWFZyUGZyMFhTVHBnOFE=
  AUTH_TOKEN: MGQ0YjFhNDg2M2IwNjE0MjA2YWUwNTI1ZWYxM2I3NDg3NDBmZTMwMjQ1ZDFhZGYzNjIyOTQ1NzFjMTBiYzExNA==
