apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus1-cluster-rolebinding
  labels:
    app.kubernetes.io/name: prometheus1-cluster-rolebinding
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent1
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus1-cluster-role
subjects:
  - kind: ServiceAccount
    name: prometheus-prometheus1-sa
    namespace: struct8-agent1
