apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-monitoring1-prometheus1
  namespace: struct8-agent1
  labels:
    struct8.io/origin: route-monitoring1
    app.kubernetes.io/name: route-monitoring1-prometheus1
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent1
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - name: gapi1
      namespace: infra1
      sectionName: g-api1
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus1-svc
          namespace: struct8-agent1
          port: 80
  hostnames:
    - prometheus.k8h.admin.billingpay.com.br
