apiVersion: v1
kind: Secret
metadata:
  name: struct8-agent1-secret
  namespace: struct8-agent1
  labels:
    app.kubernetes.io/name: struct8-agent1-secret
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent1
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
data:
  CLUSTER_API_KEY: azhzX0J0TVJrVnVlUG82S1d5YW1rV2hfMmc=
  AUTH_TOKEN: NTFmMDc2OGFmMjBjOGFlYzg4MWZlYjFiM2Y4YTU1ZTg3ZDZiNDllODVmOTI4ODIxNDFlMGFkYzQyZGViNWM2MA==
