apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-struct8-agent1-sa
  labels:
    app.kubernetes.io/name: deployment-struct8-agent1-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent1
    cloudman.io/user: rmay-struct
  namespace: struct8-agent1
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
