apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: on-line-boutique
  namespace: argocd2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: on-line-boutique
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: proj2
  source:
    repoURL: "https://github.com/Struct8/TestArgo.git"
    targetRevision: HEAD
    path: k3s/on-line-boutique/templates
  destination:
    server: "https://kubernetes.default.svc"
    namespace: online-boutique
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
