apiVersion: gateway-operator.konghq.com/v1beta1
kind: GatewayConfiguration
metadata:
  name: prod-config
  namespace: infra
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: infra
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  dataPlaneOptions:
    deployment:
      replicas: 1
      podTemplateSpec:
        spec:
          activeDeadlineSeconds: 0
          automountServiceAccountToken: false
          enableServiceLinks: false
          hostIPC: false
          hostNetwork: false
          hostPID: false
          restartPolicy: Always
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
          securityContext:
            runAsNonRoot: false
            windowsOptions:
              hostProcess: false
          serviceAccountName: deployment-kong-v1-sa
          containers:
            - image: "kong/kong:3.9"
              imagePullPolicy: Always
              name: proxy
              stdin: false
              stdinOnce: false
              tty: false
              env:
                - name: KONG_STATUS_LISTEN
                  value: "0.0.0.0:8100"
              ports:
                - name: metrics
                  containerPort: 8100
                  protocol: TCP
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"
        metadata:
          labels:
            app.kubernetes.io/name: kong
    network:
      services:
        ingress:
          type: ClusterIP
          name: kong-proxy-static
  controlPlaneOptions:
    deployment:
      replicas: 1
      podTemplateSpec:
        spec:
          containers:
            - resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
              name: controller
