apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: opentelemetry-stack2
  annotations:
    kubernetes.io/ingress.class: "kong"
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    global: "true"
    app.kubernetes.io/name: opentelemetry-stack2
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: infra
    cloudman.io/user: rmay-struct
plugin: opentelemetry
config:
  batch_span_count: 0
  batch_flush_delay: 0
  connect_timeout: 1000
  send_timeout: 5000
  read_timeout: 5000
  header_type: preserve
  sampling_rate: 0
