apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: ldap-auth-stack2
  annotations:
    kubernetes.io/ingress.class: "kong"
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    global: "true"
    app.kubernetes.io/name: ldap-auth-stack2
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: infra
    cloudman.io/user: rmay-struct
plugin: ldap_auth
config:
  ldap_port: 0
  ldaps: false
  start_tls: false
  verify_ldap_host: false
  cache_ttl: 0
  hide_credentials: false
  timeout: 0
  keepalive: 0
