apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: rate-limiting-stack
  annotations:
    kubernetes.io/ingress.class: "kong"
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    app.kubernetes.io/name: rate-limiting-stack
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: infra
    cloudman.io/user: rmay-struct
plugin: rate-limiting
config:
  second: 0
  minute: 0
  hour: 0
  day: 0
  month: 0
  year: 0
  limit_by: ip
  policy: local
  fault_tolerant: true
  hide_client_headers: false
  error_code: 429
  error_message: API rate limit exceeded
  sync_rate: 0
