apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-metrics-monitor
  labels:
    release: prom
    app.kubernetes.io/name: kong-metrics-monitor
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: infra
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  namespaceSelector:
    matchNames:
      - infra
  selector:
    matchLabels:
      app.kubernetes.io/name: kong-metrics-svc
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
