apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: session-stack2
  annotations:
    kubernetes.io/ingress.class: "kong"
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    global: "true"
    app.kubernetes.io/name: session-stack2
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Chart
    cloudman.io/user: rmay-struct
plugin: session
config:
  idling_timeout: 0
  rolling_timeout: 0
  absolute_timeout: 0
  stale_ttl: 0
  cookie_http_only: false
  cookie_secure: false
  remember: false
  remember_rolling_timeout: 0
  remember_absolute_timeout: 0
  read_body_for_logout: false
