apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus-stack2
  annotations:
    kubernetes.io/ingress.class: "kong"
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    global: "true"
    app.kubernetes.io/name: prometheus-stack2
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Chart
    cloudman.io/user: rmay-struct
plugin: prometheus
config:
  per_consumer: false
  status_code_metrics: true
  ai_metrics: false
  latency_metrics: true
  bandwidth_metrics: true
  upstream_health_metrics: true
