apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: zipkin-stack2
  annotations:
    kubernetes.io/ingress.class: "kong"
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    global: "true"
    app.kubernetes.io/name: zipkin-stack2
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Chart
    cloudman.io/user: rmay-struct
plugin: zipkin
config:
  local_service_name: kong
  sample_ratio: 0.001
  include_credential: true
  traceid_byte_count: 16
  header_type: preserve
  default_header_type: b3
  tags_header: Zipkin-Tags
  http_span_name: method
  connect_timeout: 2000
  send_timeout: 5000
  read_timeout: 5000
  phase_duration_flavor: annotations
