apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: ai-prompt-template-stack2
  annotations:
    kubernetes.io/ingress.class: "kong"
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    global: "true"
    app.kubernetes.io/name: ai-prompt-template-stack2
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Chart
    cloudman.io/user: rmay-struct
plugin: ai_prompt_template
config:
  allow_untemplated_requests: false
  log_original_request: false
  max_request_body_size: 0
