apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-1
  labels:
    app.kubernetes.io/name: game-1
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: game2048
    cloudman.io/user: rmay-struct
  namespace: ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      restartPolicy: Always
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-game-1-v1-sa
      containers:
        - image: "public.ecr.aws/l6m2t8p7/docker-2048:latest"
          imagePullPolicy: IfNotPresent
          name: game-2048
          stdin: false
          stdinOnce: false
          tty: false
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 0
            timeoutSeconds: 0
            httpGet:
              scheme: HTTP
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            failure_threshold: 0
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 0
            timeoutSeconds: 0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - readOnly: false
          startupProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
    metadata:
      labels:
        app.kubernetes.io/name: game-1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: game-1
