apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
  namespace: ns
  labels:
    app.kubernetes.io/name: deployment-svc
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: game2048
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: Deployment
  ports:
    - name: http-80
      port: 80
      targetPort: 80
      protocol: TCP
