apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-game-1-v1-sa
  labels:
    app.kubernetes.io/name: deployment-game-1-v1-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: gaming
    cloudman.io/user: rmay-struct
  namespace: gaming
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
