apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncope-console
  labels:
    app.kubernetes.io/name: syncope-console
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: State12
    cloudman.io/user: rmay-struct
  namespace: syncope
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-syncope-console-v1-sa
      containers:
        - image: "apache/syncope-console:4.1.1"
          imagePullPolicy: IfNotPresent
          name: syncope-console
          stdin: false
          stdinOnce: false
          tty: false
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: KEYMASTER_ADDRESS
              value: "http://syncope-core-8080-svc:8080/syncope/rest/keymaster"
            - name: SERVICE_DISCOVERY_ADDRESS
              value: "http://syncope-console-8080-svc:8080/syncope-console/"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: syncope-anonymous-secret
    metadata:
      labels:
        app.kubernetes.io/name: syncope-console
  selector:
    matchLabels:
      app.kubernetes.io/name: syncope-console
