apiVersion: v1
kind: Secret
metadata:
  name: syncope-db-secret
  labels:
    app.kubernetes.io/name: syncope-db-secret
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: State12
    cloudman.io/user: rmay-struct
  namespace: syncope
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  POSTGRES_PASSWORD: SyncopeDbP4ss2026
  DB_URL: "jdbc:postgresql://postgres-svc:5432/syncope?stringtype=unspecified"
  DB_USER: syncope
  DB_PASSWORD: SyncopeDbP4ss2026
wait_for_service_account_token: false
