apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
  labels:
    app.kubernetes.io/name: supermario
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  namespace: gamestest
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-supermario-v1-sa
      containers:
        - image: pengbai/docker-supermario
          imagePullPolicy: IfNotPresent
          name: supermario
          stdin: false
          stdinOnce: false
          tty: false
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
    metadata:
      labels:
        app.kubernetes.io/name: supermario
  selector:
    matchLabels:
      app.kubernetes.io/name: supermario
