apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret
  namespace: gamestest
  labels:
    app.kubernetes.io/name: secret
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  target:
    name: secret
    creationPolicy: Owner
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  dataFrom:
    - extract:
        key: Secret-k8hub
