apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paramstore
  namespace: gamestest
  labels:
    app.kubernetes.io/name: paramstore
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  target:
    name: paramstore
    creationPolicy: Owner
  secretStoreRef:
    name: aws-parameterstore
    kind: SecretStore
  data:
    - secretKey: parameter-k8hub
      remoteRef:
        key: Parameter-k8hub
