apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpressautoscaler
  namespace: gamestest
  labels:
    app.kubernetes.io/name: WordPressAutoscaler
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
