apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wp-redirect-wordpress
  namespace: gamestest
  labels:
    app.kubernetes.io/name: wp-redirect-wordpress
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - name: gapi
      namespace: infra
      sectionName: g-api-redirect
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: word-press-svc
          namespace: gamestest
          port: 80
  hostnames:
    - wp.k8h.admin.billingpay.com.br
