apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wp
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false,Delete=false"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: PVC-WP
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  namespace: gamestest
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pv-ap-pvc-wp
  storageClassName: ""
  resources:
    requests:
      storage: "5Gi"
