apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-efs
  labels:
    app.kubernetes.io/name: PVC-EFS
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  namespace: gamestest
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sc-efs-k8hub
  resources:
    requests:
      storage: "5Gi"
