apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: PVC
  labels:
    app.kubernetes.io/name: PVC
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  namespace: gamestest
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-volume-k8hub
  resources:
    requests:
      storage: "8Gi"
