apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false,Delete=false"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: pvc
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  namespace: gamestest
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pv-volume-k8hub
  storageClassName: ""
  resources:
    requests:
      storage: "8Gi"
