apiVersion: v1
kind: Secret
metadata:
  name: word-press-db-password
  labels:
    app.kubernetes.io/name: WordPressDbPassword
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  namespace: gamestest
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  password: V29yZFByZXNzUmRzMjAyNg==
