apiVersion: v1
kind: Secret
metadata:
  name: paramstore
  labels:
    app.kubernetes.io/name: paramstore
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: Games
    cloudman.io/user: rmay-struct
  namespace: gamestest
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
