apiVersion: v1
kind: Secret
metadata:
  name: struct8-agent-secret
  namespace: struct8-agent
  labels:
    app.kubernetes.io/name: struct8-agent-secret
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
data:
  CLUSTER_API_KEY: azhzX3Jva0R2UDZiQkF0eEVWd3lPUVVEYWc=
  AUTH_TOKEN: MGFjNzAzNmRlYjFkYmIxOGQ4NGI2OGU1MTBjMWE5YTVhYzM3NDBmYmFhMWMyYmYxZmYwN2RhNDI2OTQ4YmQ5Yg==
