apiVersion: v1
kind: Secret
metadata:
  name: struct8-agent-secret
  namespace: struct8-agent
  labels:
    app.kubernetes.io/name: struct8-agent-secret
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent
    cloudman.io/user: rmay-struct
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
type: Opaque
data:
  CLUSTER_API_KEY: azhzXzdZamxjNzJmYmU1NkNiZDVDLUdnZ2c=
  AUTH_TOKEN: YmY2ZGIzNTU3MmI5ZTIwMTRlMjM4NWVmYjU0NDgzNGRjZTJmM2EzN2FhOWNmNjdhMzRiNGY4MDE5ZWNkNTM3Yg==
