apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-prometheus-sa
  labels:
    app.kubernetes.io/name: prometheus-prometheus-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent
    cloudman.io/user: rmay-struct
  namespace: struct8-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
