apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-struct8-agent-sa
  labels:
    app.kubernetes.io/name: deployment-struct8-agent-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: struct8-agent
    cloudman.io/creator: rmay-struct
  namespace: struct8-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
