apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: Anderson-Dutra
  namespace: online-boutique
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  minReadySeconds: 0
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-cartservice-v1-sa
      containers:
        - image: "us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/cartservice:v0.10.6"
          imagePullPolicy: Always
          name: cartservice
          env:
            - name: REDIS_ADDR
              value: "redis-cart-svc:6379"
            - name: REDIS_CART_HOST
              value: "redis-cart-svc"
            - name: REDIS_CART_PORT
              value: "6379"
          livenessProbe:
            grpc:
              port: 7070
          ports:
            - containerPort: 7070
              name: grpc
          readinessProbe:
            grpc:
              port: 7070
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "128Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
    metadata:
      labels:
        app.kubernetes.io/name: cartservice
  selector:
    matchLabels:
      app.kubernetes.io/name: cartservice
