apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app.kubernetes.io/name: loadgenerator
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: Anderson-Dutra
  namespace: online-boutique
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  minReadySeconds: 0
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-loadgenerator-v1-sa
      containers:
        - image: "us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/loadgenerator:v0.10.6"
          imagePullPolicy: Always
          name: loadgenerator
          env:
            - name: FRONTEND_ADDR
              value: "frontend-svc:8080"
            - name: USERS
              value: "10"
            - name: RATE
              value: "1"
            - name: FRONTEND_HOST
              value: "frontend-svc"
            - name: FRONTEND_PORT
              value: "8080"
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
    metadata:
      labels:
        app.kubernetes.io/name: loadgenerator
  selector:
    matchLabels:
      app.kubernetes.io/name: loadgenerator
