apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app.kubernetes.io/name: shippingservice
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: Anderson-Dutra
  namespace: online-boutique
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  minReadySeconds: 0
  paused: false
  progressDeadlineSeconds: 0
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-shippingservice-v1-sa
      containers:
        - image: "us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/shippingservice:v0.10.6"
          imagePullPolicy: Always
          name: shippingservice
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"
          livenessProbe:
            grpc:
              port: 50051
          ports:
            - containerPort: 50051
              name: grpc
          readinessProbe:
            grpc:
              port: 50051
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
    metadata:
      labels:
        app.kubernetes.io/name: shippingservice
  selector:
    matchLabels:
      app.kubernetes.io/name: shippingservice
