apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app.kubernetes.io/name: adservice
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: Anderson-Dutra
  namespace: online-boutique
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  minReadySeconds: 0
  paused: false
  progressDeadlineSeconds: 0
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      serviceAccountName: deployment-adservice-v1-sa
      containers:
        - image: "us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/adservice:v0.10.6"
          imagePullPolicy: Always
          name: adservice
          env:
            - name: PORT
              value: "9555"
          livenessProbe:
            grpc:
              port: 9555
          ports:
            - containerPort: 9555
              name: grpc
          readinessProbe:
            grpc:
              port: 9555
          resources:
            requests:
              cpu: "200m"
              memory: "180Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
    metadata:
      labels:
        app.kubernetes.io/name: adservice
  selector:
    matchLabels:
      app.kubernetes.io/name: adservice
