apiVersion: v1
kind: Service
metadata:
  name: redis-cart-svc
  namespace: online-boutique
  labels:
    app.kubernetes.io/name: redis-cart-svc
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: Anderson-Dutra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: redis-cart
  ports:
    - name: port-6379
      port: 6379
      targetPort: 6379
      protocol: TCP
