apiVersion: v1
kind: Service
metadata:
  name: adservice-svc
  namespace: online-boutique
  labels:
    app.kubernetes.io/name: adservice-svc
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: Anderson-Dutra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: adservice
  ports:
    - name: port-9555
      port: 9555
      targetPort: 9555
      protocol: TCP
