apiVersion: v1
kind: Service
metadata:
  name: checkoutservice-svc
  namespace: online-boutique
  labels:
    app.kubernetes.io/name: checkoutservice-svc
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: Anderson-Dutra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: checkoutservice
  ports:
    - name: port-5050
      port: 5050
      targetPort: 5050
      protocol: TCP
