apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-checkoutservice-v1-sa
  labels:
    app.kubernetes.io/name: deployment-checkoutservice-v1-sa
    app.kubernetes.io/managed-by: struct8
    app.kubernetes.io/instance: on-line-boutique
    cloudman.io/creator: Anderson-Dutra
  namespace: online-boutique
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
